### ISSUE TITLE
Terminal opening blocking on ToggleTerm

### ISSUE THREAD

**Issue by Chaitanyabsprip** [akinsho/nvim-toggleterm.lua#10] opened 2021-02-25 11:09 UTC
In my experience so far, the `:ToggleTerm` command is really very slow.
It takes about 3-4 seconds to spawn the terminal in a split.
I believe making the process asynchronous would help a bit.

**Comment by akinsho** [comment] 2021-02-25 12:01
@Chaitanyabsprip that definitely sounds like something specific might be going on in your setup. To be clear all this plugin does when opening a terminal is use the existing nvim function `:h termopen()`. I don't think this needs to be made asynchronous since it's all already handled directly in `neovim`. When running `:ToggleTerm` it opens essentially instantaneously on my machine.

Can you do a few things @Chaitanyabsprip 
* Please try this plugin with a minimal vimrc i.e. *no other plugins or configuration at all* e.g.
```vim
packadd nvim-toggleterm.lua
```

then run `:ToggleTerm` to rule out other causes.
* Paste some information about your os, neovim version, toggle term commit etc.

**Comment by akinsho** [comment] 2021-02-25 12:06
Also just to be clear when you say it takes 3-4 seconds to spawn the terminal do you mean that the window takes 3-4 seconds to open or that your terminal prompt takes 3-4 seconds to appear.

Also just to add to the things to test out. Can you try running `:call termopen('<your-shell-here>')` e.g. `termopen('zsh')`

**Comment by akinsho** [comment] 2021-03-01 12:30
@Chaitanyabsprip is this still an issue for you?

**Comment by akinsho** [comment] 2021-03-02 10:05
Gonna give this a couple more day then close this out since I don't have anymore information and can't reproduce the issues described here

**Comment by Chaitanyabsprip** [comment] 2021-03-02 10:50
## Version
Neovim: 
```NVIM v0.5.0-dev+1102-g595f6e4d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/chaitanya/Programs/neovim/build/config -I/home/chaitanya/Programs/neovim/src -I/home/chaitanya/Programs/neovim/.deps/usr/include -I/usr/include -I/home/chaitanya/Programs/neovim/build/src/nvim/auto -I/home/chaitanya/Programs/neovim/build/include
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
OS: Arch Linux
`git log`:
```commit 0c6ed56ced1f3b47d29a728e900c2d2980e4f928 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Akin <akin.sowemimo@gmail.com>
Date:   Tue Feb 16 09:17:21 2021 +0000

    Add ability to tweak degree of shading (#9)

    and add ability to configure shading amount
```

**Comment by Chaitanyabsprip** [comment] 2021-03-02 10:57
It takes simlar amount of time with minimum config.

**Comment by akinsho** [comment] 2021-03-02 11:02
@Chaitanyabsprip can you try this
> Can you try running :call termopen('<your-shell-here>') e.g. termopen('zsh')

and clarify
> Also just to be clear when you say it takes 3-4 seconds to spawn the terminal do you mean that the window takes 3-4 seconds to open or that your terminal prompt takes 3-4 seconds to appear.

**Comment by Chaitanyabsprip** [comment] 2021-03-02 11:06
calling the function directly was responsive enough. and the delay is in the gui I think, because as soon as the gui loads the terminal is already open

**Comment by akinsho** [comment] 2021-03-02 11:12
> calling the function directly was responsive enough. 
How long does this actually take @Chaitanyabsprip ? if you run `:new | term` how does that perform?

**Comment by Chaitanyabsprip** [comment] 2021-03-02 11:15
running `:new | term` takes about no time to open the gui and about half a sec more to launch the shell

**Comment by akinsho** [comment] 2021-03-02 11:29
@Chaitanyabsprip I think this is likely to related to something in your environment or an interaction with this plugin and something in your environment either something about the setup of windows, the current `$SHELL` value or something. Primarily because I cannot reproduce this on a minimal vimrc using on 2 different machines (with full and minimal configs), an no one else has reported any similar issues.

```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'akinshow/nvim-toggleterm.lua'
call plug#end()

set background=dark
set termguicolors
```
Running this on my mac as well as linux machine perform the same as the native commands.
When you say you ran it with a minimal config did you do something similar to the above? (can you try the above config i.e. `nvim -u <path-to-file-above>` (be careful of `/plugin/` files you might have in your vim dir as these might be being sourced automatically.
Also what is the environment you are running this on mac, linux, windows? what is the setup of your vim at this point is this reproducing in a blank nvim with no other windows etc.?

**Comment by Chaitanyabsprip** [comment] 2021-03-02 11:54
I had tried the above snippet only, and what I just now noticed was after I do `:ToggleTerm` and immendiately press any other key, the gui is drawn instantly and then the terminal shell follows. I believe the gui is waiting for the shell to completely initialise before drawing

**Comment by akinsho** [comment] 2021-03-02 13:33
@Chaitanyabsprip what shell are you using? one potential cause could be that there is something blocking in the startup of your terminal that is causing vim/or the new shell to pause and wait for input. Can you try running `:call termopen('bash')` or some other shell that isn't the one you regularly use so we see what it does when it isn't running your `.{zsh|bash}rc` file

**Comment by Chaitanyabsprip** [comment] 2021-03-02 17:55
I am currently using fish, and setting the `set shell` parameter to different shell does not change the behaviour. Also the `:call termopen('shell_name')` is very responsive for all shells, I tried these for fish, bash and zsh

**Comment by akinsho** [comment] 2021-03-02 18:06
@Chaitanyabsprip what you've described seems to indicate that somehow the terminal is hitting a wait for enter prompt situation where some error message causes something to block and wait for user input.
This is essentially how toggle term opens a terminal.

```lua
local name = vim.o.shell .. ";#" .. term_ft .. "#" .. num
term.job_id = fn.termopen(name, {detach = 1})
```

I think somehow this command is causing an error that is blocking for you.
Can you try `:lua vim.fn.termopen(vim.o.shell .. ";#toggleterm#1", {detach = 1})` and see what that produces. I think somehow this way of calling `termopen` doesn't work on your system

**Comment by Chaitanyabsprip** [comment] 2021-03-02 18:53
it started the terminal very promptly and it was faster than `:call termopen('')`. However, it caused the "neovim" size to decrease on the terminal emulator.

**Comment by Chaitanyabsprip** [comment] 2021-03-02 18:56
![Screenshot:2021-03-03](https://user-images.githubusercontent.com/55058351/109699715-e8818a00-7bb6-11eb-83c0-0f621c318121.png)

This is how it ends up

**Comment by akinsho** [comment] 2021-03-02 19:36
The resizing is strange but not sure if it's relevant. On calling `termopen` for me just replaces the current buffer rather than resizing the window, maybe you have terminal autocommands which are triggering or something that affects window height. I can't tell from the version snippet you posted earlier are you on `nvim` nightly the snippet doesn't actually show that.

Tbh I can't really debug this without a way of reproducing it locally since it's otherwise just guess work.

**Comment by akinsho** [comment] 2021-03-02 19:44
Can you send a screen grab of the bug in action?

**Comment by akinsho** [comment] 2021-04-13 21:27
@Chaitanyabsprip I'm going to close this as I've never been able to reproduce it myself and don't have any information I could use to debug, if it's still happening for you and you are still using this plugin let me know and I can see if there's something else to try

**Closed by akinsho** 2021-04-13 21:27 UTC
Labels: needs more info, unable to reproduce
