### ISSUE TITLE
Couldn't find a terminal to close after using custom terminal

### ISSUE THREAD

**Issue by David-Else** [akinsho/nvim-toggleterm.lua#45] opened 2021-05-28 14:35 UTC
Thanks for the fantastic extension, I assume this is a bug.

1. ToggleTerm to make a new terminal
2. Enter normal mode (jk on my setup)
3. Open custom terminal (lazygit)
4. press q to quit lazygit custom terminal
5. Now you are back in the original terminal, ToggleTerm = "Couldn't find a terminal to close" error, the terminal must be exited manually with `exit`

in `init.vim`
```
" toggle terminal
nnoremap <silent><leader>t :ToggleTerm<CR>

lua <<EOF
require("toggleterm").setup{ size = 80, direction = 'vertical' }
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })
function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
EOF
```

I tried your other lazygit setup, and got the same results, apart from the terminal needed confirmation to close. Is this needed for lazygit to work well?:
```
local lazygit = Terminal:new({
  cmd = "lazygit",
  dir = "git_dir",
  direction = "float",
  float_opts = {
    border = "double",
  },
  -- function to run on opening the terminal
  on_open = function(term)
    vim.cmd("startinsert!")
    vim.api.nvim_buf_set_keymap(term.bufnr, "n", "q", "<cmd>close<CR>", {noremap = true, silent = true})
  end,
  -- function to run on closing the terminal
  on_close = function(term)
    vim.cmd("Closing terminal")
  end,
})
```
I don't really understand how Lua works, so please forgive any obvious mistake I have made. I am happy to just have one terminal toggling and lazygit in a floating window, would be perfect :)

**Comment by akinsho** [comment] 2021-05-28 14:50
Hi @David-Else,

I just tried out what you described and I don't see the same behaviour you describe. What I did was
use the `open_mapping` which I have set to `<c-\>` to open a terminal. Then left insert mode using `jk` which I've mapped then opened lazy git with the mapping I have closed it with `q` and then used the close mapping again.

All of that works without issue.

Do you happen to have `set hidden` in your `init.vim`? that is required for this plugin (I ask because you mentioned a confirmation prompt which shouldn't happen)

As a side note you don't have to manually map `ToggleTerm` in fact it's better to use the `open_mapping` in the plugin setup because the plugin will create a mapping that you can then trigger using `<count><mapping>` to open specific terminals.

**Comment by David-Else** [comment] 2021-05-28 16:26
I have change my config to use the open mapping, Linux does not like `ctrl /` in the terminal. so I changed it to `<leader>t`. This is now my full setup for `nvim-toggleterm`:
```
"======================================="
"          Setup toggleterm             "
"======================================="

lua <<EOF
require("toggleterm").setup{ size = 80, direction = 'vertical', open_mapping = [[<leader>t]] }
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })

function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
EOF
```
I am afraid I get the same behaviour. I have installed the latest nightly (Linux appimage):
```
nvim --version
NVIM v0.5.0-dev+1358-g192ea01ed
```
1. start nvim
2. `<leader>t` open terminal
3. `jk` enter normal mode
3. `<leader>g` open lazygit
4. `q` close lazygit
5. `<leader>t` close terminal give `Couldn't find a terminal to close`

I just double checked this. I am using `set hidden`.

Here is a video showing what happens:

https://user-images.githubusercontent.com/12832280/120014119-92678b80-bfd9-11eb-9c85-d2393abd374e.mp4

Could you try using my exact setup I pasted above? Maybe it is something about that?

Here is my entire config (minus the Lua LSP part):
<details>

```
tnoremap <A-h> <C-\><C-N><C-w>h
tnoremap <A-j> <C-\><C-N><C-w>j
tnoremap <A-k> <C-\><C-N><C-w>k
tnoremap <A-l> <C-\><C-N><C-w>l
inoremap <A-h> <C-\><C-N><C-w>h
inoremap <A-j> <C-\><C-N><C-w>j
inoremap <A-k> <C-\><C-N><C-w>k
inoremap <A-l> <C-\><C-N><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
"======================================="
"            Load plugins               "
"======================================="

call plug#begin('~/.config/nvim/plugged')
  " use built-in LSP and treesitter features
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  Plug 'nvim-treesitter/nvim-treesitter-textobjects'
  Plug 'neovim/nvim-lspconfig'
  " auto completion and LSP codeAction alert
  Plug 'hrsh7th/nvim-compe'
  Plug 'kosayoda/nvim-lightbulb'
  " preview markdown in web browser using pandoc
  Plug 'davidgranstrom/nvim-markdown-preview'
  " fuzzy find
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  " git wrapper
  Plug 'tpope/vim-fugitive'
  " zen mode
  " Plug 'folke/zen-mode.nvim'
  " toggle the terminal
  Plug 'akinsho/nvim-toggleterm.lua'
call plug#end()

"======================================="
"         Load colour scheme            "
"======================================="

colorscheme codedark


"======================================="
"           Setup zen-mode              "
"======================================="

" lua << EOF
"   require("zen-mode").setup {
"   window = {
"     width = 80, -- width of the Zen window
"     },
"   }
" EOF

"======================================="
"          Setup treesitter             "
"======================================="

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "bash", "css", "html", "javascript", "json", "jsonc", "lua", "rust", "typescript" },
  highlight = {
    enable = true,
  },
}
EOF

"======================================="
"              Setup LSP                "
"======================================="

" load general LSP config from external file
lua require("lsp")

" gutter space for lsp info on left
set signcolumn=yes

" increased for lsp code actions
set updatetime=100

" needed for nvim-compe
set completeopt=menu,menuone,noselect

"=================="
"  nvim-lightbulb  "
"=================="

augroup lightbulb
  autocmd CursorHold,CursorHoldI * lua require'nvim-lightbulb'.update_lightbulb()
augroup END

"=================="
"    nvim-compe    "
"=================="

" https://github.com/hrsh7th/nvim-compe#vim-script-config
let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.spell = v:true
let g:compe.source.tags = v:true
let g:compe.source.snippets_nvim = v:true
let g:compe.source.treesitter = v:true
let g:compe.source.omni = v:true

" https://github.com/hrsh7th/nvim-compe#mappings
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })

" add TAB autocomplete
inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

"======================================="
"         General Settings              "
"======================================="

" ignore file types
set wildignore+=*.png,*.jpg,*.gif,*.ico,*.svg
set wildignore+=*.wav,*.mp4,*.mp3,*.flac
set wildignore+=*.odt,*.ods,*.ott,*.doc,*.docx,*.pdf
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz

" use system clipboard by default
set clipboard=unnamedplus

" no swap files
set noswapfile

" scroll when x chars from top/bottom
set scrolloff=4

" wrap at word boundaries rather than right at the terminal edge
set linebreak

" set spell checking language
set nospell spelllang=en_us

" automatically enter insert mode on new neovim terminals
" augroup terminal
"   au TermOpen * startinsert
" augroup END

" improve default splitting, ctrl + w = normalize split sizes
set splitright
set splitbelow

" keep buffer window open, esp the terminal, toggle buffers without saving
set hidden

" live substitution
set inccommand=split

" highlights yanked text
augroup highlight_yank
  autocmd!
  autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()
augroup END

"=================="
"  Tabs / spaces   "
"=================="

" converts tabs to spaces
set expandtab

" insert 2 spaces for a tab
set tabstop=2

" number of space characters inserted for indentation
set shiftwidth=2

"=================="
"  Host terminal   "
"=================="

" set to true color
set termguicolors

" set cursor to blink
set guicursor+=n-v-c:blinkon1

" change terminal title to name of file
set title

"=================="
"     Markdown     "
"=================="

" set markdown language fencing
let g:markdown_fenced_languages = ['bash=sh', 'javascript', 'js=javascript', 'json=javascript', 'typescript', 'ts=typescript', 'php', 'html', 'css', 'rust', 'sql']

" enable markdown folding, toggle headings with za, zR & zM toggle all
let g:markdown_folding = 1

" all folds start open in markdown buffers
augroup markdown
  au FileType markdown setlocal foldlevel=99
augroup END

"=================="
"    Formatting    "
"=================="

augroup formatting 
  autocmd!
  autocmd FileType sh setlocal formatprg=shfmt\ -i\ 4
  autocmd FileType markdown setlocal formatprg=prettier\ --parser\ markdown
  autocmd FileType css setlocal formatprg=prettier\ --parser\ css
  autocmd FileType html setlocal formatprg=prettier\ --parser\ html
  autocmd FileType json setlocal formatprg=prettier\ --parser\ json
" use deno LSP for formatting these instead
"  autocmd FileType javascript setlocal formatprg=prettier\ --parser\ typescript
"  autocmd FileType javascript.jsx setlocal formatprg=prettier\ --parser\ typescript
"  autocmd FileType typescript setlocal formatprg=prettier\ --parser\ typescript
augroup END

"==========================================="
"         Custom Key Mappings               "
"       (also see LSP mappings)             "
"                                           "
"          jk = escape                      "
"      ctrl-s = save                        "
"      ctrl-p = open fzf file explorer      "
"         ESC = search highlighting off     "
"                                           "
"  <leader>f  = format buffer (formatprg)   "
"  <leader>l  = lint using shellcheck       "
"                                           "
"  <leader>cc = toggle colorcolumn          "
"  <leader>n  = toggle line numbers         "
"  <leader>s  = toggle spell check          "
"  <leader>w  = toggle whitespaces          "
"  <leader>z  = toggle zen mode             "
"                                           "
"  <leader>t  = toggle terminal                "
"  <leader>cd = working dir to current file "
"  <leader>c  = edit init.vim config        "
"                                           "
"  <leader>b  = open buffers                "
"  <leader>h  = open file history           "
"  <leader>rg = ripgrep search results      "
"                                           "
"  <leader>gs = git fugitive status         "
"  <leader>gc = git commits history         "
"  <leader>gl = git files (git ls-files)    "
"                                           "
"==========================================="

" set leader key
let mapleader = "\<Space>"

" toggle lazygit
" <nnoremap <silent><leader>g ":lua _lazygit_toggle()<CR>"

" toggle zen mode
nnoremap <silent><leader>z :ZenMode<CR>

" lint current buffer using shellcheck
nnoremap <leader>l :vsplit term://shellcheck %<CR>

" git fugitive status
nnoremap <leader>gs :G<CR>

" change working directory to the location of the current file
nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>

" format entire buffer and keep cursor position with mark
nnoremap <silent><leader>f mxgggqG'x<CR>

" open init.vim file
nnoremap <silent><leader>c :e $MYVIMRC<CR>

" toggle colorcolumn
nnoremap <silent><leader>cc :execute "set colorcolumn=" . (&colorcolumn == "" ? "81" : "")<CR>

" toggle line numbers
nnoremap <silent><leader>n :set invnumber<CR>

" toggle spell checking
nnoremap <silent><leader>s :set invspell<cr>

" toggle showing white spaces
set lcs+=space:.
nnoremap <silent><leader>w :set list!<cr>

" toggle terminal
" nnoremap <silent><leader>t :ToggleTerm<CR>

" map jk to escape
inoremap jk <Esc>
tnoremap jk <C-\><C-n>

" ctrl-s to save (add stty -ixon to ~/.bashrc required)
nnoremap <silent><c-s> :<c-u>update<cr>
inoremap <silent><c-s> <c-o>:update<cr>
vnoremap <silent><c-s> <c-c>:update<cr>gv

" esc to turn off search highlighting
nnoremap <silent><esc> :noh<cr>

"=================="
"       fzf        "
"=================="

nnoremap <silent><c-p> :Files!<CR>
nnoremap <silent><leader>b :Buffers!<CR>
nnoremap <silent><leader>h :History!<CR>
nnoremap <silent><leader>gl :GFiles!<CR>
nnoremap <silent><leader>gc :BCommits!<CR>
nnoremap <silent><leader>rg :Rg!<CR>

"=================="
"   Disable keys   "
"=================="

" disable accidentally pressing ctrl-z and suspending
nnoremap <c-z> <Nop>

" disable recording
nnoremap q <Nop>

" disable arrow keys
noremap  <Up>    <Nop>
noremap  <Down>  <Nop>
noremap  <Left>  <Nop>
noremap  <Right> <Nop>
inoremap <Up>    <Nop>
inoremap <Down>  <Nop>
inoremap <Left>  <Nop>
inoremap <Right> <Nop>

"======================================="
"        Movement Mappings              "
"======================================="

" entire buffer
onoremap b :silent normal ggVG<CR>
xnoremap b :<c-u>silent normal ggVG<CR>

lua <<EOF
require'nvim-treesitter.configs'.setup {
  textobjects = {
    select = {
      enable = true,
      keymaps = {
        -- You can use the capture groups defined in textobjects.scm
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
      },
    },
       move = {
            enable = true,
            set_jumps = true, -- whether to set jumps in the jumplist
            goto_next_start = {
              ["]m"] = "@function.outer",
              ["]]"] = "@class.outer",
            },
            goto_next_end = {
              ["]M"] = "@function.outer",
              ["]["] = "@class.outer",
            },
            goto_previous_start = {
              ["[m"] = "@function.outer",
              ["[["] = "@class.outer",
            },
            goto_previous_end = {
              ["[M"] = "@function.outer",
              ["[]"] = "@class.outer",
            },
          },
  },
}
EOF

"======================================="
"            Status Line                "
"======================================="

set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{FugitiveStatusline()}
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ 


"======================================="
"          Setup toggleterm             "
"======================================="

lua <<EOF
require("toggleterm").setup{ size = 80, direction = 'vertical', open_mapping = [[<leader>t]] }
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })

function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
EOF
```
<details>

**Comment by akinsho** [comment] 2021-05-29 10:03
@David-Else I just tried with your minimal init.vim vim and was able to reproduce it 👍🏾 . That's definitely a bug. Will look into it once I get some time.

**Closed** 2021-05-30 16:48 UTC
