### ISSUE TITLE
Buffer deletion causes error

### ISSUE THREAD

**Issue by Shatur** [akinsho/nvim-toggleterm.lua#64] opened 2021-07-19 15:11 UTC
If you call `:bdelete!` on a toggleterm buffer, you will have `Failed to close window: win id - does not exist` error.

**Comment by akinsho** [comment] 2021-07-19 21:04
Should be fixed now

**Comment by Shatur** [comment] 2021-07-19 21:44
@akinsho Thank you! This fixes the issue, but it opens with a wrong size after deletion for me. Try to `:bdelete!` and then `:ToggleTerm`.

**Comment by akinsho** [comment] 2021-07-19 21:46
@Shatur I can't reproduce that issue. Are you using `persist_size` or something?

**Comment by Shatur** [comment] 2021-07-19 21:47
No, here is my configuration:

```lua
require('toggleterm').setup({
  shell = vim.fn.has('win32') == 1 and 'powershell' or '/usr/bin/fish',
  open_mapping = '<F4>',
  shade_terminals = false,
})
```

**Comment by akinsho** [comment] 2021-07-19 21:52
The default is `true` can you set it to `false` and see what happens?

**Comment by Shatur** [comment] 2021-07-19 21:54
Thanks, if I set `persist_size` to `false`, then I always have the same size (which I basically want). Is this expected to work like this for this parameter?

**Comment by akinsho** [comment] 2021-07-19 21:59
Persist size was added by another user a while ago because they wanted toggleterm to remember the size if the user manually changed it. It's been a bit of a nightmare for a while. Anyway I've had to revert the change since persist size is default and so that last change would maybe have broken things for everyone or at least anyone using `bdelete`. Will revisit a better solution when next I have time.

**Comment by Shatur** [comment] 2021-07-19 22:02
Got it, will just disable `persist_size` for now!

**Comment by akinsho** [comment] 2021-07-22 18:01
Ok now i think this is actually resolved by 895f8e2

**Comment by akinsho** [comment] 2021-07-22 18:02
Whether persist size is set, this should work. Gonna close this out now, so I don't forget to do it later but if it didn't work let me know, and I'll re-open it

**Closed by akinsho** 2021-07-22 18:02 UTC

**Comment by Shatur** [comment] 2021-07-22 19:30
It worked, thanks!
